# Site settings
title: Genki Kondo
description: Genki Kondo's Personal Webpage

# User settings
username: Genki Kondo
user_title: Software Engineer
email: kondo.genki@gmail.com
# twitter_username: lorem_ipsum
instagram_username: genkikondo
facebook_username: kondo.genki
linkedin_username: genkikondo
github_username:  genkikondo
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

